<?php

use Illuminate\Database\Seeder;
use App\Municipio;

class MunicipioTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Municipio::create(['nombre'=>'Guatemala','codigo'=>101,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'Santa Catarina Pinula','codigo'=>102,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'San José Pinula','codigo'=>103,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'San José del Golfo','codigo'=>104,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'Palencia','codigo'=>105,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'Chinautla','codigo'=>106,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'San Pedro Ayampuc','codigo'=>107,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'Mixco','codigo'=>108,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'San Pedro Sacatepéquez','codigo'=>109,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'San Juan Sacatepéquez','codigo'=>110,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'San Raymundo','codigo'=>111,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'Chuarrancho','codigo'=>112,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'Fraijanes','codigo'=>113,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'Amatitlán','codigo'=>114,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'Villa Nueva','codigo'=>115,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'Villa Canales','codigo'=>116,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'Petapa','codigo'=>117,'departamento_id'=>1]);
        Municipio::create(['nombre'=>'Guastatoya','codigo'=>201,'departamento_id'=>2]);
        Municipio::create(['nombre'=>'Morazán','codigo'=>202,'departamento_id'=>2]);
        Municipio::create(['nombre'=>'San Agustín Acasaguastlán','codigo'=>203,'departamento_id'=>2]);
        Municipio::create(['nombre'=>'San Cristóbal Acasaguastlán','codigo'=>204,'departamento_id'=>2]);
        Municipio::create(['nombre'=>'El Jícaro','codigo'=>205,'departamento_id'=>2]);
        Municipio::create(['nombre'=>'Sansare','codigo'=>206,'departamento_id'=>2]);
        Municipio::create(['nombre'=>'Sanarate','codigo'=>207,'departamento_id'=>2]);
        Municipio::create(['nombre'=>'San Antonio la Paz','codigo'=>208,'departamento_id'=>2]);
        Municipio::create(['nombre'=>'Antigua Guatemala','codigo'=>301,'departamento_id'=>3]);
        Municipio::create(['nombre'=>'Jocotenango','codigo'=>302,'departamento_id'=>3]);
        Municipio::create(['nombre'=>'Pastores','codigo'=>303,'departamento_id'=>3]);
        Municipio::create(['nombre'=>'Sumpango','codigo'=>304,'departamento_id'=>3]);
        Municipio::create(['nombre'=>'Santo Domingo Xenacoj','codigo'=>305,'departamento_id'=>3]);
        Municipio::create(['nombre'=>'Santiago Sacatepéquez','codigo'=>306,'departamento_id'=>3]);
        Municipio::create(['nombre'=>'San Bartolomé Milpas Altas','codigo'=>307,'departamento_id'=>3]);
        Municipio::create(['nombre'=>'San Lucas Sacatepéquez','codigo'=>308,'departamento_id'=>3]);
        Municipio::create(['nombre'=>'Santa Lucía Milpas Altas','codigo'=>309,'departamento_id'=>3]);
        Municipio::create(['nombre'=>'Magdalena Milpas Altas','codigo'=>310,'departamento_id'=>3]);
        Municipio::create(['nombre'=>'Santa María de Jesús','codigo'=>311,'departamento_id'=>3]);
        Municipio::create(['nombre'=>'Ciudad Vieja','codigo'=>312,'departamento_id'=>3]);
        Municipio::create(['nombre'=>'San Miguel Dueñas','codigo'=>313,'departamento_id'=>3]);
        Municipio::create(['nombre'=>'Alotenango','codigo'=>314,'departamento_id'=>3]);
        Municipio::create(['nombre'=>'San Antonio Aguas Calientes','codigo'=>315,'departamento_id'=>3]);
        Municipio::create(['nombre'=>'Santa Catarina Barahona','codigo'=>316,'departamento_id'=>3]);
        Municipio::create(['nombre'=>'Chimaltenango','codigo'=>401,'departamento_id'=>4]);
        Municipio::create(['nombre'=>'San José Poaquil','codigo'=>402,'departamento_id'=>4]);
        Municipio::create(['nombre'=>'San Martín Jilotepeque','codigo'=>403,'departamento_id'=>4]);
        Municipio::create(['nombre'=>'Comalapa','codigo'=>404,'departamento_id'=>4]);
        Municipio::create(['nombre'=>'Santa Apolonia','codigo'=>405,'departamento_id'=>4]);
        Municipio::create(['nombre'=>'Tecpán Guatemala','codigo'=>406,'departamento_id'=>4]);
        Municipio::create(['nombre'=>'Patzún','codigo'=>407,'departamento_id'=>4]);
        Municipio::create(['nombre'=>'Pochuta','codigo'=>408,'departamento_id'=>4]);
        Municipio::create(['nombre'=>'Patzicía','codigo'=>409,'departamento_id'=>4]);
        Municipio::create(['nombre'=>'Santa Cruz Balanyá','codigo'=>410,'departamento_id'=>4]);
        Municipio::create(['nombre'=>'Acatenango','codigo'=>411,'departamento_id'=>4]);
        Municipio::create(['nombre'=>'Yepocapa','codigo'=>412,'departamento_id'=>4]);
        Municipio::create(['nombre'=>'San Andrés Itzapa','codigo'=>413,'departamento_id'=>4]);
        Municipio::create(['nombre'=>'Parramos','codigo'=>414,'departamento_id'=>4]);
        Municipio::create(['nombre'=>'Zaragoza','codigo'=>415,'departamento_id'=>4]);
        Municipio::create(['nombre'=>'El Tejar','codigo'=>416,'departamento_id'=>4]);
        Municipio::create(['nombre'=>'Escuintla','codigo'=>501,'departamento_id'=>5]);
        Municipio::create(['nombre'=>'Santa Lucía Cotzumalguapa','codigo'=>502,'departamento_id'=>5]);
        Municipio::create(['nombre'=>'La Democracia','codigo'=>503,'departamento_id'=>5]);
        Municipio::create(['nombre'=>'Siquinalá','codigo'=>504,'departamento_id'=>5]);
        Municipio::create(['nombre'=>'Masagua','codigo'=>505,'departamento_id'=>5]);
        Municipio::create(['nombre'=>'Tiquisate','codigo'=>506,'departamento_id'=>5]);
        Municipio::create(['nombre'=>'La Gomera','codigo'=>507,'departamento_id'=>5]);
        Municipio::create(['nombre'=>'Guanagazapa','codigo'=>508,'departamento_id'=>5]);
        Municipio::create(['nombre'=>'San José','codigo'=>509,'departamento_id'=>5]);
        Municipio::create(['nombre'=>'Iztapa','codigo'=>510,'departamento_id'=>5]);
        Municipio::create(['nombre'=>'Palín','codigo'=>511,'departamento_id'=>5]);
        Municipio::create(['nombre'=>'San Vicente Pacaya','codigo'=>512,'departamento_id'=>5]);
        Municipio::create(['nombre'=>'Nueva Concepción','codigo'=>513,'departamento_id'=>5]);
        Municipio::create(['nombre'=>'Sipacate','codigo'=>514,'departamento_id'=>5]);
        Municipio::create(['nombre'=>'Cuilapa','codigo'=>601,'departamento_id'=>6]);
        Municipio::create(['nombre'=>'Barberena','codigo'=>602,'departamento_id'=>6]);
        Municipio::create(['nombre'=>'Santa Rosa de Lima','codigo'=>603,'departamento_id'=>6]);
        Municipio::create(['nombre'=>'Casillas','codigo'=>604,'departamento_id'=>6]);
        Municipio::create(['nombre'=>'San Rafael las Flores','codigo'=>605,'departamento_id'=>6]);
        Municipio::create(['nombre'=>'Oratorio','codigo'=>606,'departamento_id'=>6]);
        Municipio::create(['nombre'=>'San Juan Tecuaco','codigo'=>607,'departamento_id'=>6]);
        Municipio::create(['nombre'=>'Chiquimulilla','codigo'=>608,'departamento_id'=>6]);
        Municipio::create(['nombre'=>'Taxisco','codigo'=>609,'departamento_id'=>6]);
        Municipio::create(['nombre'=>'Santa María Ixhuatán','codigo'=>610,'departamento_id'=>6]);
        Municipio::create(['nombre'=>'Guazacapán','codigo'=>611,'departamento_id'=>6]);
        Municipio::create(['nombre'=>'Santa Cruz Naranjo','codigo'=>612,'departamento_id'=>6]);
        Municipio::create(['nombre'=>'Pueblo Nuevo Viñas','codigo'=>613,'departamento_id'=>6]);
        Municipio::create(['nombre'=>'Nueva Santa Rosa','codigo'=>614,'departamento_id'=>6]);
        Municipio::create(['nombre'=>'Sololá','codigo'=>701,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'San José Chacayá','codigo'=>702,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'Santa María Visitación','codigo'=>703,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'Santa Lucía Utatlán','codigo'=>704,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'Nahualá','codigo'=>705,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'Santa Catarina Ixtahuacán','codigo'=>706,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'Santa Clara la Laguna','codigo'=>707,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'Concepción','codigo'=>708,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'San Andrés Semetabaj','codigo'=>709,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'Panajachel','codigo'=>710,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'Santa Catarina Palopó','codigo'=>711,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'San Antonio Palopó','codigo'=>712,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'San Lucas Tolimán','codigo'=>713,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'Santa Cruz la Laguna','codigo'=>714,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'San Pablo la Laguna','codigo'=>715,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'San Marcos la Laguna','codigo'=>716,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'San Juan la Laguna','codigo'=>717,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'San Pedro la Laguna','codigo'=>718,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'Santiago Atitlán','codigo'=>719,'departamento_id'=>7]);
        Municipio::create(['nombre'=>'Totonicapán','codigo'=>801,'departamento_id'=>8]);
        Municipio::create(['nombre'=>'San Cristóbal Totonicapán','codigo'=>802,'departamento_id'=>8]);
        Municipio::create(['nombre'=>'San Francisco el Alto','codigo'=>803,'departamento_id'=>8]);
        Municipio::create(['nombre'=>'San Andrés Xecul','codigo'=>804,'departamento_id'=>8]);
        Municipio::create(['nombre'=>'Momostenango','codigo'=>805,'departamento_id'=>8]);
        Municipio::create(['nombre'=>'Santa María Chiquimula','codigo'=>806,'departamento_id'=>8]);
        Municipio::create(['nombre'=>'Santa Lucía la Reforma','codigo'=>807,'departamento_id'=>8]);
        Municipio::create(['nombre'=>'San Bartolo','codigo'=>808,'departamento_id'=>8]);
        Municipio::create(['nombre'=>'Quetzaltenango','codigo'=>901,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Salcajá','codigo'=>902,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Olintepeque','codigo'=>903,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'San Carlos Sija','codigo'=>904,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Sibilia','codigo'=>905,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Cabricán','codigo'=>906,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Cajolá','codigo'=>907,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'San Miguel Siguilá','codigo'=>908,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Ostuncalco','codigo'=>909,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'San Mateo','codigo'=>910,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Concepción Chiquirichapa','codigo'=>911,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'San Martín Sacatepéquez','codigo'=>912,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Almolonga','codigo'=>913,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Cantel','codigo'=>914,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Huitán','codigo'=>915,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Zunil','codigo'=>916,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Colomba','codigo'=>917,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'San Francisco la Unión','codigo'=>918,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'El Palmar','codigo'=>919,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Coatepeque','codigo'=>920,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Génova','codigo'=>921,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Flores Costa Cuca','codigo'=>922,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'La Esperanza','codigo'=>923,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Palestina de los Altos','codigo'=>924,'departamento_id'=>9]);
        Municipio::create(['nombre'=>'Mazatenango','codigo'=>1001,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'Cuyotenango','codigo'=>1002,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'San Francisco Zapotitlán','codigo'=>1003,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'San Bernardino','codigo'=>1004,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'San José el Idolo','codigo'=>1005,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'Santo Domingo Suchitepéquez','codigo'=>1006,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'San Lorenzo','codigo'=>1007,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'Samayac','codigo'=>1008,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'San Pablo Jocopilas','codigo'=>1009,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'San Antonio Suchitepéquez','codigo'=>1010,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'San Miguel Panán','codigo'=>1011,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'San Gabriel','codigo'=>1012,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'Chicacao','codigo'=>1013,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'Patulul','codigo'=>1014,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'Santa Bárbara','codigo'=>1015,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'San Juan Bautista','codigo'=>1016,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'Santo Tomás la Unión','codigo'=>1017,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'Zunilito','codigo'=>1018,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'Pueblo Nuevo','codigo'=>1019,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'Río Bravo','codigo'=>1020,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'San José La Máquina','codigo'=>1021,'departamento_id'=>10]);
        Municipio::create(['nombre'=>'Retalhuleu','codigo'=>1101,'departamento_id'=>11]);
        Municipio::create(['nombre'=>'San Sebastián','codigo'=>1102,'departamento_id'=>11]);
        Municipio::create(['nombre'=>'Santa Cruz Muluá','codigo'=>1103,'departamento_id'=>11]);
        Municipio::create(['nombre'=>'San Martín Zapotitlán','codigo'=>1104,'departamento_id'=>11]);
        Municipio::create(['nombre'=>'San Felipe','codigo'=>1105,'departamento_id'=>11]);
        Municipio::create(['nombre'=>'San Andrés Villa Seca','codigo'=>1106,'departamento_id'=>11]);
        Municipio::create(['nombre'=>'Champerico','codigo'=>1107,'departamento_id'=>11]);
        Municipio::create(['nombre'=>'Nuevo San Carlos','codigo'=>1108,'departamento_id'=>11]);
        Municipio::create(['nombre'=>'El Asintal','codigo'=>1109,'departamento_id'=>11]);
        Municipio::create(['nombre'=>'San Marcos','codigo'=>1201,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'San Pedro Sacatepéquez','codigo'=>1202,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'San Antonio Sacatepéquez','codigo'=>1203,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Comitancillo','codigo'=>1204,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'San Miguel Ixtahuacán','codigo'=>1205,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Concepción Tutuapa','codigo'=>1206,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Tacaná','codigo'=>1207,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Sibinal','codigo'=>1208,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Tajumulco','codigo'=>1209,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Tejutla','codigo'=>1210,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'San Rafael Pié de la Cuesta','codigo'=>1211,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Nuevo Progreso','codigo'=>1212,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'El Tumbador','codigo'=>1213,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'El Rodeo','codigo'=>1214,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Malacatán','codigo'=>1215,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Catarina','codigo'=>1216,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Ayutla','codigo'=>1217,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Ocós','codigo'=>1218,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'San Pablo','codigo'=>1219,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'El Quetzal','codigo'=>1220,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'La Reforma','codigo'=>1221,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Pajapita','codigo'=>1222,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Ixchiguán','codigo'=>1223,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'San José Ojetenán','codigo'=>1224,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'San Cristóbal Cucho','codigo'=>1225,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Sipacapa','codigo'=>1226,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Esquipulas Palo Gordo','codigo'=>1227,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Río Blanco','codigo'=>1228,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'San Lorenzo','codigo'=>1229,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'La Blanca','codigo'=>1230,'departamento_id'=>12]);
        Municipio::create(['nombre'=>'Huehuetenango','codigo'=>1301,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Chiantla','codigo'=>1302,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Malacatancito','codigo'=>1303,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Cuilco','codigo'=>1304,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Nentón','codigo'=>1305,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'San Pedro Necta','codigo'=>1306,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Jacaltenango','codigo'=>1307,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Soloma','codigo'=>1308,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Ixtahuacán','codigo'=>1309,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Santa Bárbara','codigo'=>1310,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'La Libertad','codigo'=>1311,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'La Democracia','codigo'=>1312,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'San Miguel Acatán','codigo'=>1313,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'San Rafael la Independencia','codigo'=>1314,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Todos Santos Cuchumatán','codigo'=>1315,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'San Juan Atitán','codigo'=>1316,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Santa Eulalia','codigo'=>1317,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'San Mateo Ixtatán','codigo'=>1318,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Colotenango','codigo'=>1319,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'San Sebastián Huehuetenango','codigo'=>1320,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Tectitán','codigo'=>1321,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Concepción Huista','codigo'=>1322,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'San Juan Ixcoy','codigo'=>1323,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'San Antonio Huista','codigo'=>1324,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'San Sebastián Coatán','codigo'=>1325,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Barillas','codigo'=>1326,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Aguacatán','codigo'=>1327,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'San Rafael Petzal','codigo'=>1328,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'San Gaspar Ixchil','codigo'=>1329,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Santiago Chimaltenango','codigo'=>1330,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Santa Ana Huista','codigo'=>1331,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Unión Cantinil','codigo'=>1332,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Petatan','codigo'=>1333,'departamento_id'=>13]);
        Municipio::create(['nombre'=>'Santa Cruz del Quiché','codigo'=>1401,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'Chiché','codigo'=>1402,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'Chinique','codigo'=>1403,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'Zacualpa','codigo'=>1404,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'Chajul','codigo'=>1405,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'Chichicastenango','codigo'=>1406,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'Patzité','codigo'=>1407,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'San Antonio Ilotenango','codigo'=>1408,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'San Pedro Jocopilas','codigo'=>1409,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'Cunén','codigo'=>1410,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'San Juan Cotzal','codigo'=>1411,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'Joyabaj','codigo'=>1412,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'Nebaj','codigo'=>1413,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'San Andrés Sajcabajá','codigo'=>1414,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'Uspantán','codigo'=>1415,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'Sacapulas','codigo'=>1416,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'San Bartolomé Jocotenango','codigo'=>1417,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'Canillá','codigo'=>1418,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'Chicamán','codigo'=>1419,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'Ixcán','codigo'=>1420,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'Pachalum','codigo'=>1421,'departamento_id'=>14]);
        Municipio::create(['nombre'=>'Salamá','codigo'=>1501,'departamento_id'=>15]);
        Municipio::create(['nombre'=>'San Miguel Chicaj','codigo'=>1502,'departamento_id'=>15]);
        Municipio::create(['nombre'=>'Rabinal','codigo'=>1503,'departamento_id'=>15]);
        Municipio::create(['nombre'=>'Cubulco','codigo'=>1504,'departamento_id'=>15]);
        Municipio::create(['nombre'=>'Granados','codigo'=>1505,'departamento_id'=>15]);
        Municipio::create(['nombre'=>'El Chol','codigo'=>1506,'departamento_id'=>15]);
        Municipio::create(['nombre'=>'San Jerónimo','codigo'=>1507,'departamento_id'=>15]);
        Municipio::create(['nombre'=>'Purulhá','codigo'=>1508,'departamento_id'=>15]);
        Municipio::create(['nombre'=>'Cobán','codigo'=>1601,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'Santa Cruz Verapaz','codigo'=>1602,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'San Cristóbal Verapaz','codigo'=>1603,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'Tactic','codigo'=>1604,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'Tamahú','codigo'=>1605,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'Tucurú','codigo'=>1606,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'Panzós','codigo'=>1607,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'Senahú','codigo'=>1608,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'San Pedro Carchá','codigo'=>1609,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'San Juan Chamelco','codigo'=>1610,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'Lanquín','codigo'=>1611,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'Cahabón','codigo'=>1612,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'Chisec','codigo'=>1613,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'Chahal','codigo'=>1614,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'Fray Bartolomé de las Casas','codigo'=>1615,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'Santa Catalina la Tinta','codigo'=>1616,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'Raxruhá','codigo'=>1617,'departamento_id'=>16]);
        Municipio::create(['nombre'=>'Flores','codigo'=>1701,'departamento_id'=>17]);
        Municipio::create(['nombre'=>'San José','codigo'=>1702,'departamento_id'=>17]);
        Municipio::create(['nombre'=>'San Benito','codigo'=>1703,'departamento_id'=>17]);
        Municipio::create(['nombre'=>'San Andrés','codigo'=>1704,'departamento_id'=>17]);
        Municipio::create(['nombre'=>'La Libertad','codigo'=>1705,'departamento_id'=>17]);
        Municipio::create(['nombre'=>'San Francisco','codigo'=>1706,'departamento_id'=>17]);
        Municipio::create(['nombre'=>'Santa Ana','codigo'=>1707,'departamento_id'=>17]);
        Municipio::create(['nombre'=>'Dolores','codigo'=>1708,'departamento_id'=>17]);
        Municipio::create(['nombre'=>'San Luis','codigo'=>1709,'departamento_id'=>17]);
        Municipio::create(['nombre'=>'Sayaxché','codigo'=>1710,'departamento_id'=>17]);
        Municipio::create(['nombre'=>'Melchor de Mencos','codigo'=>1711,'departamento_id'=>17]);
        Municipio::create(['nombre'=>'Poptún','codigo'=>1712,'departamento_id'=>17]);
        Municipio::create(['nombre'=>'Las Cruces','codigo'=>1713,'departamento_id'=>17]);
        Municipio::create(['nombre'=>'El Chal','codigo'=>1714,'departamento_id'=>17]);
        Municipio::create(['nombre'=>'Puerto Barrios','codigo'=>1801,'departamento_id'=>18]);
        Municipio::create(['nombre'=>'Livingston','codigo'=>1802,'departamento_id'=>18]);
        Municipio::create(['nombre'=>'El Estor','codigo'=>1803,'departamento_id'=>18]);
        Municipio::create(['nombre'=>'Morales','codigo'=>1804,'departamento_id'=>18]);
        Municipio::create(['nombre'=>'Los Amates','codigo'=>1805,'departamento_id'=>18]);
        Municipio::create(['nombre'=>'Zacapa','codigo'=>1901,'departamento_id'=>19]);
        Municipio::create(['nombre'=>'Estanzuela','codigo'=>1902,'departamento_id'=>19]);
        Municipio::create(['nombre'=>'Río Hondo','codigo'=>1903,'departamento_id'=>19]);
        Municipio::create(['nombre'=>'Gualán','codigo'=>1904,'departamento_id'=>19]);
        Municipio::create(['nombre'=>'Teculután','codigo'=>1905,'departamento_id'=>19]);
        Municipio::create(['nombre'=>'Usumatlán','codigo'=>1906,'departamento_id'=>19]);
        Municipio::create(['nombre'=>'Cabañas','codigo'=>1907,'departamento_id'=>19]);
        Municipio::create(['nombre'=>'San Diego','codigo'=>1908,'departamento_id'=>19]);
        Municipio::create(['nombre'=>'La Unión','codigo'=>1909,'departamento_id'=>19]);
        Municipio::create(['nombre'=>'Huité','codigo'=>1910,'departamento_id'=>19]);
        Municipio::create(['nombre'=>'San Jorge','codigo'=>1911,'departamento_id'=>19]);
        Municipio::create(['nombre'=>'Chiquimula','codigo'=>2001,'departamento_id'=>20]);
        Municipio::create(['nombre'=>'San José La Arada','codigo'=>2002,'departamento_id'=>20]);
        Municipio::create(['nombre'=>'San Juan Ermita','codigo'=>2003,'departamento_id'=>20]);
        Municipio::create(['nombre'=>'Jocotán','codigo'=>2004,'departamento_id'=>20]);
        Municipio::create(['nombre'=>'Camotán','codigo'=>2005,'departamento_id'=>20]);
        Municipio::create(['nombre'=>'Olopa','codigo'=>2006,'departamento_id'=>20]);
        Municipio::create(['nombre'=>'Esquipulas','codigo'=>2007,'departamento_id'=>20]);
        Municipio::create(['nombre'=>'Concepción Las Minas','codigo'=>2008,'departamento_id'=>20]);
        Municipio::create(['nombre'=>'Quetzaltepeque','codigo'=>2009,'departamento_id'=>20]);
        Municipio::create(['nombre'=>'San Jacinto','codigo'=>2010,'departamento_id'=>20]);
        Municipio::create(['nombre'=>'Ipala','codigo'=>2011,'departamento_id'=>20]);
        Municipio::create(['nombre'=>'Jalapa','codigo'=>2101,'departamento_id'=>21]);
        Municipio::create(['nombre'=>'San Pedro Pinula','codigo'=>2102,'departamento_id'=>21]);
        Municipio::create(['nombre'=>'San Luis Jilotepeque','codigo'=>2103,'departamento_id'=>21]);
        Municipio::create(['nombre'=>'San Manuel Chaparrón','codigo'=>2104,'departamento_id'=>21]);
        Municipio::create(['nombre'=>'San Carlos Alzatate','codigo'=>2105,'departamento_id'=>21]);
        Municipio::create(['nombre'=>'Monjas','codigo'=>2106,'departamento_id'=>21]);
        Municipio::create(['nombre'=>'Mataquescuintla','codigo'=>2107,'departamento_id'=>21]);
        Municipio::create(['nombre'=>'Jutiapa','codigo'=>2201,'departamento_id'=>22]);
        Municipio::create(['nombre'=>'El Progreso','codigo'=>2202,'departamento_id'=>22]);
        Municipio::create(['nombre'=>'Santa Catarina Mita','codigo'=>2203,'departamento_id'=>22]);
        Municipio::create(['nombre'=>'Agua Blanca','codigo'=>2204,'departamento_id'=>22]);
        Municipio::create(['nombre'=>'Asunción Mita','codigo'=>2205,'departamento_id'=>22]);
        Municipio::create(['nombre'=>'Yupiltepeque','codigo'=>2206,'departamento_id'=>22]);
        Municipio::create(['nombre'=>'Atescatempa','codigo'=>2207,'departamento_id'=>22]);
        Municipio::create(['nombre'=>'Jerez','codigo'=>2208,'departamento_id'=>22]);
        Municipio::create(['nombre'=>'El Adelanto','codigo'=>2209,'departamento_id'=>22]);
        Municipio::create(['nombre'=>'Zapotitlán','codigo'=>2210,'departamento_id'=>22]);
        Municipio::create(['nombre'=>'Comapa','codigo'=>2211,'departamento_id'=>22]);
        Municipio::create(['nombre'=>'Jalpatagua','codigo'=>2212,'departamento_id'=>22]);
        Municipio::create(['nombre'=>'Conguaco','codigo'=>2213,'departamento_id'=>22]);
        Municipio::create(['nombre'=>'Moyuta','codigo'=>2214,'departamento_id'=>22]);
        Municipio::create(['nombre'=>'Pasaco','codigo'=>2215,'departamento_id'=>22]);
        Municipio::create(['nombre'=>'San José Acatempa','codigo'=>2216,'departamento_id'=>22]);
        Municipio::create(['nombre'=>'Quesada','codigo'=>2217,'departamento_id'=>22]);

    }
}
